name: Build Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -

      - name: Add Poetry to PATH
        # shell: powershell
        # run: |
        #   $env:Path += ";$env:APPDATA\Python\Scripts"
        #   echo "::add-path::$env:APPDATA\Python\Scripts"
      - name: Add Poetry to PATH
        run: echo "%APPDATA%\Python\Scripts" >> $GITHUB_ENV

      - name: Install dependencies
        run: poetry install

      - name: Build executable with PyInstaller
        run: |
          poetry run pyinstaller --onefile main.py

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: dist/*.exe
